### ISSUE TITLE
Majestict to Google Data / Looker Studio connector down?

### ISSUE THREAD

**Issue by datasbravas** [Gladior-B-V/majestic-connector#1]
Hi guys,

So, I'm working for an agency. We built for a client a Google Data / Looker studio dashboard using your connector.

It was maybe a month ago.

We already had issues when you updated it (categorized the metrics, which means we had to re-do everything), and now since last week it's not working anymore.

Have you changed anything? Is there anything we can do to fix the issue?

![image](https://user-images.githubusercontent.com/104200281/207825824-f8fe59c3-97fe-409a-a10a-4faec9e4b2ec.png)

Please let us know urgently!

Cheers,

Arnaud

**Comment by daannijkamp** [comment]
@datasbravas Hi Arnaud, 

I'm sorry to hear you're experiencing issues with the Majestic Connector.
Nothing has changed lately. I can't find anything in the log files either. 

Could you perhaps email your "profile code" to data-dashboards@gladior.com ? 
(datahubapp.gladior.com -> Edit profile -> At the bottom of the page)

Then I can take a closer look at what went wrong.

![Screenshot from 2022-12-19 11-56-19](https://user-images.githubusercontent.com/1774060/208410584-9e1ce7af-bbee-4fd8-a0ce-68758911f375.png)

**Comment by datasbravas** [comment]
@daannijkamp ,

E-mail sent, thanks!

**Comment by zoedufrenne** [comment]
Hi @datasbravas,

There was a bug in the code and we've fixed it. So the connector should work. Could you let us know if everything works? 
Don't "refresh fields" otherwise you need to make a new connection.

**Comment by datasbravas** [comment]
It's indeed working, thanks @zoedufrenne
