### ISSUE TITLE
Issue: data imported to Looker are incorrect

### ISSUE THREAD

**Issue by valterndou** [Gladior-B-V/majestic-connector#2]
Hello,

Firstly thank you very much for this connector! 
I want to report some issues that i have noticed:
- citation flow and trust flow (in my case) are different from what I see in Majestic (both historical and recent);
- I'm missing some backlinks I can see in Majestic and i know for sure are active
- Anchor text is almost always missing

Let me know if you need any other information.

Thank you very much.

Cheers.

**Comment by zoedufrenne** [comment]
HI @valterndou 

Sorry for responding so late. 
We are indeed seeing less data in our dashboard. I will check with our developers and keep you posted. 

Zoé Gerritsen

**Comment by zoedufrenne** [comment]
Hi @valterndou, We've tested the conector and it looks like it's fixxed. Can you verify?
